// AUTO-GENERATED by scripts/build-pricing.mjs — do not edit by hand.
// CSV 갱신 시 `npm run build:pricing` 재실행 후 commit.
// 단위: 만원. `bojeung`만 인원수.

import type { UserRegion } from '../types';

export type DressBase = '본식만' | '본식촬영' | '촬영만';
export type MakeupGrade = '실장' | '부원장' | '원장';

export type CategoryBaseSeason = {
  studio: number;
  dress: Record<DressBase, number>;
  makeup: Record<MakeupGrade, number>;
};

export type CategoryBase = {
  peak: CategoryBaseSeason;
  offPeak: CategoryBaseSeason;
};

export const CATEGORY_BASE: Record<UserRegion, CategoryBase> = {
  "서울": {
    "peak": {
      "studio": 138,
      "dress": {
        "본식만": 137,
        "본식촬영": 155,
        "촬영만": 136
      },
      "makeup": {
        "실장": 67,
        "부원장": 74,
        "원장": 83
      }
    },
    "offPeak": {
      "studio": 141,
      "dress": {
        "본식만": 138,
        "본식촬영": 155,
        "촬영만": 137
      },
      "makeup": {
        "실장": 67,
        "부원장": 74,
        "원장": 83
      }
    }
  },
  "수도권": {
    "peak": {
      "studio": 117,
      "dress": {
        "본식만": 145,
        "본식촬영": 163,
        "촬영만": 144
      },
      "makeup": {
        "실장": 64,
        "부원장": 80,
        "원장": 87
      }
    },
    "offPeak": {
      "studio": 119,
      "dress": {
        "본식만": 146,
        "본식촬영": 163,
        "촬영만": 144
      },
      "makeup": {
        "실장": 65,
        "부원장": 80,
        "원장": 88
      }
    }
  },
  "광역시": {
    "peak": {
      "studio": 135,
      "dress": {
        "본식만": 149,
        "본식촬영": 163,
        "촬영만": 147
      },
      "makeup": {
        "실장": 50,
        "부원장": 54,
        "원장": 59
      }
    },
    "offPeak": {
      "studio": 135,
      "dress": {
        "본식만": 149,
        "본식촬영": 163,
        "촬영만": 147
      },
      "makeup": {
        "실장": 50,
        "부원장": 54,
        "원장": 59
      }
    }
  },
  "이외": {
    "peak": {
      "studio": 123,
      "dress": {
        "본식만": 125,
        "본식촬영": 137,
        "촬영만": 124
      },
      "makeup": {
        "실장": 56,
        "부원장": 55,
        "원장": 58
      }
    },
    "offPeak": {
      "studio": 123,
      "dress": {
        "본식만": 125,
        "본식촬영": 137,
        "촬영만": 124
      },
      "makeup": {
        "실장": 56,
        "부원장": 55,
        "원장": 58
      }
    }
  }
};
