// AUTO-GENERATED by scripts/build-pricing.mjs — do not edit by hand.
// CSV 갱신 시 `npm run build:pricing` 재실행 후 commit.
// 단위: 만원. `bojeung`만 인원수.

import type { UserRegion } from '../types';

export type DressBase = '본식만' | '본식촬영' | '촬영만';
export type MakeupGrade = '실장' | '부원장' | '원장';

export type CategoryBaseSeason = {
  studio: number;
  dress: Record<DressBase, number>;
  makeup: Record<MakeupGrade, number>;
};

export type CategoryBase = {
  peak: CategoryBaseSeason;
  offPeak: CategoryBaseSeason;
};

export const CATEGORY_BASE: Record<UserRegion, CategoryBase> = {
  "서울": {
    "peak": {
      "studio": 139,
      "dress": {
        "본식만": 131,
        "본식촬영": 150,
        "촬영만": 130
      },
      "makeup": {
        "실장": 66,
        "부원장": 75,
        "원장": 86
      }
    },
    "offPeak": {
      "studio": 141,
      "dress": {
        "본식만": 134,
        "본식촬영": 155,
        "촬영만": 134
      },
      "makeup": {
        "실장": 66,
        "부원장": 76,
        "원장": 86
      }
    }
  },
  "수도권": {
    "peak": {
      "studio": 110,
      "dress": {
        "본식만": 144,
        "본식촬영": 160,
        "촬영만": 141
      },
      "makeup": {
        "실장": 63,
        "부원장": 79,
        "원장": 87
      }
    },
    "offPeak": {
      "studio": 111,
      "dress": {
        "본식만": 144,
        "본식촬영": 161,
        "촬영만": 142
      },
      "makeup": {
        "실장": 63,
        "부원장": 79,
        "원장": 87
      }
    }
  },
  "광역시": {
    "peak": {
      "studio": 136,
      "dress": {
        "본식만": 147,
        "본식촬영": 161,
        "촬영만": 145
      },
      "makeup": {
        "실장": 48,
        "부원장": 53,
        "원장": 58
      }
    },
    "offPeak": {
      "studio": 137,
      "dress": {
        "본식만": 147,
        "본식촬영": 161,
        "촬영만": 146
      },
      "makeup": {
        "실장": 48,
        "부원장": 52,
        "원장": 58
      }
    }
  },
  "이외": {
    "peak": {
      "studio": 123,
      "dress": {
        "본식만": 125,
        "본식촬영": 138,
        "촬영만": 125
      },
      "makeup": {
        "실장": 55,
        "부원장": 55,
        "원장": 60
      }
    },
    "offPeak": {
      "studio": 123,
      "dress": {
        "본식만": 125,
        "본식촬영": 137,
        "촬영만": 125
      },
      "makeup": {
        "실장": 56,
        "부원장": 56,
        "원장": 60
      }
    }
  }
};
