// AUTO-GENERATED by scripts/build-pricing.mjs — do not edit by hand.
// CSV 갱신 시 `npm run build:pricing` 재실행 후 commit.
// 단위: 만원. `bojeung`만 인원수.

import type { UserRegion } from '../types';

export type SeasonProfile = {
  bojeung: number;       // 최소 보증 인원
  perHead: number;       // 1인당 식대 (만원)
  daegwan: number;       // 대관 비용 (만원)
  baseMeal: number;      // 기본 식대 총금액 (만원)
  baseDecoration: number; // 기본 장식비 (만원)
};

export type RegionProfile = {
  peak: SeasonProfile;
  offPeak: SeasonProfile;
};

export const REGION_PROFILES: Record<UserRegion, RegionProfile> = {
  "서울": {
    "peak": {
      "bojeung": 218,
      "perHead": 8,
      "daegwan": 638,
      "baseMeal": 1835,
      "baseDecoration": 0
    },
    "offPeak": {
      "bojeung": 215,
      "perHead": 9,
      "daegwan": 639,
      "baseMeal": 1828,
      "baseDecoration": 0
    }
  },
  "수도권": {
    "peak": {
      "bojeung": 200,
      "perHead": 7,
      "daegwan": 422,
      "baseMeal": 1306,
      "baseDecoration": 0
    },
    "offPeak": {
      "bojeung": 200,
      "perHead": 7,
      "daegwan": 421,
      "baseMeal": 1302,
      "baseDecoration": 0
    }
  },
  "광역시": {
    "peak": {
      "bojeung": 192,
      "perHead": 6,
      "daegwan": 221,
      "baseMeal": 1013,
      "baseDecoration": 6
    },
    "offPeak": {
      "bojeung": 192,
      "perHead": 6,
      "daegwan": 223,
      "baseMeal": 1012,
      "baseDecoration": 5
    }
  },
  "이외": {
    "peak": {
      "bojeung": 198,
      "perHead": 5,
      "daegwan": 239,
      "baseMeal": 1016,
      "baseDecoration": 0
    },
    "offPeak": {
      "bojeung": 197,
      "perHead": 5,
      "daegwan": 241,
      "baseMeal": 1004,
      "baseDecoration": 0
    }
  }
};
