// AUTO-GENERATED by scripts/build-pricing.mjs — do not edit by hand.
// CSV 갱신 시 `npm run build:pricing` 재실행 후 commit.
// 단위: 만원. `bojeung`만 인원수.

import type { UserRegion } from '../types';

export type SeasonProfile = {
  bojeung: number;       // 최소 보증 인원
  perHead: number;       // 1인당 식대 (만원)
  daegwan: number;       // 대관 비용 (만원)
  baseMeal: number;      // 기본 식대 총금액 (만원)
  baseDecoration: number; // 기본 장식비 (만원)
};

export type RegionProfile = {
  peak: SeasonProfile;
  offPeak: SeasonProfile;
};

export const REGION_PROFILES: Record<UserRegion, RegionProfile> = {
  "서울": {
    "peak": {
      "bojeung": 218,
      "perHead": 8,
      "daegwan": 654,
      "baseMeal": 1775,
      "baseDecoration": 0
    },
    "offPeak": {
      "bojeung": 215,
      "perHead": 8,
      "daegwan": 655,
      "baseMeal": 1769,
      "baseDecoration": 0
    }
  },
  "수도권": {
    "peak": {
      "bojeung": 200,
      "perHead": 7,
      "daegwan": 444,
      "baseMeal": 1292,
      "baseDecoration": 0
    },
    "offPeak": {
      "bojeung": 200,
      "perHead": 7,
      "daegwan": 461,
      "baseMeal": 1294,
      "baseDecoration": 0
    }
  },
  "광역시": {
    "peak": {
      "bojeung": 192,
      "perHead": 5,
      "daegwan": 224,
      "baseMeal": 1005,
      "baseDecoration": 6
    },
    "offPeak": {
      "bojeung": 192,
      "perHead": 5,
      "daegwan": 222,
      "baseMeal": 995,
      "baseDecoration": 5
    }
  },
  "이외": {
    "peak": {
      "bojeung": 202,
      "perHead": 5,
      "daegwan": 247,
      "baseMeal": 1005,
      "baseDecoration": 0
    },
    "offPeak": {
      "bojeung": 196,
      "perHead": 5,
      "daegwan": 255,
      "baseMeal": 965,
      "baseDecoration": 0
    }
  }
};
