// AUTO-GENERATED by scripts/build-pricing.mjs — do not edit by hand.
// CSV 갱신 시 `npm run build:pricing` 재실행 후 commit.
// 단위: 만원. `bojeung`만 인원수.

import type { ToggleId, UserRegion } from '../types';

export type TogglePriceSeason = {
  peak: number | null;
  offPeak: number | null;
};

export const TOGGLE_PRICES: Record<ToggleId, Record<UserRegion, TogglePriceSeason>> = {
  "원본 구매": {
    "서울": {
      "peak": 39,
      "offPeak": 39
    },
    "수도권": {
      "peak": 39,
      "offPeak": 39
    },
    "광역시": {
      "peak": 23,
      "offPeak": 23
    },
    "이외": {
      "peak": 21,
      "offPeak": 21
    }
  },
  "담당자 지정": {
    "서울": {
      "peak": 17,
      "offPeak": 17
    },
    "수도권": {
      "peak": 17,
      "offPeak": 17
    },
    "광역시": {
      "peak": 20,
      "offPeak": 20
    },
    "이외": {
      "peak": 21,
      "offPeak": 20
    }
  },
  "서브 스냅": {
    "서울": {
      "peak": 17,
      "offPeak": 17
    },
    "수도권": {
      "peak": 17,
      "offPeak": 17
    },
    "광역시": {
      "peak": 17,
      "offPeak": 17
    },
    "이외": {
      "peak": 19,
      "offPeak": 19
    }
  },
  "야외 촬영": {
    "서울": {
      "peak": 11,
      "offPeak": 11
    },
    "수도권": {
      "peak": 11,
      "offPeak": 11
    },
    "광역시": {
      "peak": 15,
      "offPeak": 15
    },
    "이외": {
      "peak": 16,
      "offPeak": 16
    }
  },
  "얼리스타트": {
    "서울": {
      "peak": 6,
      "offPeak": 6
    },
    "수도권": {
      "peak": 8,
      "offPeak": 8
    },
    "광역시": {
      "peak": 5,
      "offPeak": 5
    },
    "이외": {
      "peak": 5,
      "offPeak": 5
    }
  },
  "앨범페이지 추가": {
    "서울": {
      "peak": 3,
      "offPeak": 3
    },
    "수도권": {
      "peak": 3,
      "offPeak": 3
    },
    "광역시": {
      "peak": 4,
      "offPeak": 4
    },
    "이외": {
      "peak": 3,
      "offPeak": 3
    }
  },
  "드레스 추가": {
    "서울": {
      "peak": 20,
      "offPeak": 20
    },
    "수도권": {
      "peak": 20,
      "offPeak": 20
    },
    "광역시": {
      "peak": 20,
      "offPeak": 20
    },
    "이외": {
      "peak": 20,
      "offPeak": 20
    }
  },
  "모바일 사진 제공": {
    "서울": {
      "peak": 10,
      "offPeak": 10
    },
    "수도권": {
      "peak": 10,
      "offPeak": 10
    },
    "광역시": {
      "peak": 10,
      "offPeak": 10
    },
    "이외": {
      "peak": 10,
      "offPeak": 10
    }
  },
  "수정본구매비": {
    "서울": {
      "peak": 14,
      "offPeak": 14
    },
    "수도권": {
      "peak": 14,
      "offPeak": 14
    },
    "광역시": {
      "peak": 20,
      "offPeak": 20
    },
    "이외": {
      "peak": 19,
      "offPeak": 20
    }
  },
  "촬영시간 추가": {
    "서울": {
      "peak": 11,
      "offPeak": 11
    },
    "수도권": {
      "peak": 11,
      "offPeak": 11
    },
    "광역시": {
      "peak": 10,
      "offPeak": 10
    },
    "이외": {
      "peak": 11,
      "offPeak": 11
    }
  },
  "드레스 지정": {
    "서울": {
      "peak": 74,
      "offPeak": 80
    },
    "수도권": {
      "peak": 70,
      "offPeak": 80
    },
    "광역시": {
      "peak": 165,
      "offPeak": 165
    },
    "이외": {
      "peak": 128,
      "offPeak": 129
    }
  },
  "본식 헬퍼": {
    "서울": {
      "peak": 25,
      "offPeak": 25
    },
    "수도권": {
      "peak": 25,
      "offPeak": 25
    },
    "광역시": {
      "peak": 22,
      "offPeak": 22
    },
    "이외": {
      "peak": 24,
      "offPeak": 24
    }
  },
  "2부 드레스": {
    "서울": {
      "peak": 50,
      "offPeak": 50
    },
    "수도권": {
      "peak": 46,
      "offPeak": 44
    },
    "광역시": {
      "peak": 33,
      "offPeak": 33
    },
    "이외": {
      "peak": 36,
      "offPeak": 36
    }
  },
  "퍼스트웨어": {
    "서울": {
      "peak": 107,
      "offPeak": 107
    },
    "수도권": {
      "peak": 107,
      "offPeak": 106
    },
    "광역시": {
      "peak": 114,
      "offPeak": 125
    },
    "이외": {
      "peak": 173,
      "offPeak": 181
    }
  },
  "가봉 스냅": {
    "서울": {
      "peak": 75,
      "offPeak": 75
    },
    "수도권": {
      "peak": 75,
      "offPeak": 75
    },
    "광역시": {
      "peak": 76,
      "offPeak": 76
    },
    "이외": {
      "peak": 58,
      "offPeak": 58
    }
  },
  "턱시도 대여": {
    "서울": {
      "peak": 25,
      "offPeak": 24
    },
    "수도권": {
      "peak": 23,
      "offPeak": 23
    },
    "광역시": {
      "peak": 18,
      "offPeak": 18
    },
    "이외": {
      "peak": 15,
      "offPeak": 15
    }
  },
  "촬영 헬퍼": {
    "서울": {
      "peak": 25,
      "offPeak": 25
    },
    "수도권": {
      "peak": 25,
      "offPeak": 25
    },
    "광역시": {
      "peak": 19,
      "offPeak": 19
    },
    "이외": {
      "peak": 22,
      "offPeak": 22
    }
  },
  "혼주 메이크업": {
    "서울": {
      "peak": 20,
      "offPeak": 20
    },
    "수도권": {
      "peak": 20,
      "offPeak": 20
    },
    "광역시": {
      "peak": 11,
      "offPeak": 11
    },
    "이외": {
      "peak": 15,
      "offPeak": 14
    }
  },
  "헤어변형": {
    "서울": {
      "peak": 35,
      "offPeak": 35
    },
    "수도권": {
      "peak": 35,
      "offPeak": 35
    },
    "광역시": {
      "peak": 17,
      "offPeak": 17
    },
    "이외": {
      "peak": 29,
      "offPeak": 29
    }
  },
  "신랑 메이크업": {
    "서울": {
      "peak": 20,
      "offPeak": 20
    },
    "수도권": {
      "peak": 20,
      "offPeak": 20
    },
    "광역시": {
      "peak": 20,
      "offPeak": 20
    },
    "이외": {
      "peak": 20,
      "offPeak": 20
    }
  },
  "휴무일 진행비": {
    "서울": {
      "peak": 21,
      "offPeak": 21
    },
    "수도권": {
      "peak": 21,
      "offPeak": 21
    },
    "광역시": {
      "peak": 8,
      "offPeak": 8
    },
    "이외": {
      "peak": 5,
      "offPeak": 5
    }
  },
  "촬영 출장비": {
    "서울": {
      "peak": 15,
      "offPeak": 15
    },
    "수도권": {
      "peak": 15,
      "offPeak": 15
    },
    "광역시": {
      "peak": 22,
      "offPeak": 22
    },
    "이외": {
      "peak": 16,
      "offPeak": 16
    }
  },
  "헤어피스 시술": {
    "서울": {
      "peak": 11,
      "offPeak": 11
    },
    "수도권": {
      "peak": 11,
      "offPeak": 11
    },
    "광역시": {
      "peak": 13,
      "offPeak": 13
    },
    "이외": {
      "peak": 9,
      "offPeak": 10
    }
  },
  "생화 꽃장식": {
    "서울": {
      "peak": 501,
      "offPeak": 519
    },
    "수도권": {
      "peak": 393,
      "offPeak": 406
    },
    "광역시": {
      "peak": 157,
      "offPeak": 155
    },
    "이외": {
      "peak": 125,
      "offPeak": 127
    }
  },
  "부케": {
    "서울": {
      "peak": 29,
      "offPeak": 29
    },
    "수도권": {
      "peak": 29,
      "offPeak": 29
    },
    "광역시": {
      "peak": 18,
      "offPeak": 17
    },
    "이외": {
      "peak": 23,
      "offPeak": 23
    }
  },
  "플라워 샤워": {
    "서울": {
      "peak": 22,
      "offPeak": 22
    },
    "수도권": {
      "peak": 19,
      "offPeak": 19
    },
    "광역시": {
      "peak": 10,
      "offPeak": 10
    },
    "이외": {
      "peak": 10,
      "offPeak": 10
    }
  },
  "포토테이블": {
    "서울": {
      "peak": 36,
      "offPeak": 37
    },
    "수도권": {
      "peak": 37,
      "offPeak": 37
    },
    "광역시": {
      "peak": 37,
      "offPeak": 37
    },
    "이외": {
      "peak": 37,
      "offPeak": 37
    }
  },
  "웨딩 케이크": {
    "서울": {
      "peak": 44,
      "offPeak": 45
    },
    "수도권": {
      "peak": 42,
      "offPeak": 43
    },
    "광역시": {
      "peak": 30,
      "offPeak": 30
    },
    "이외": {
      "peak": 28,
      "offPeak": 26
    }
  },
  "본식 원판 구매": {
    "서울": {
      "peak": 51,
      "offPeak": 51
    },
    "수도권": {
      "peak": 51,
      "offPeak": 51
    },
    "광역시": {
      "peak": 50,
      "offPeak": 50
    },
    "이외": {
      "peak": 50,
      "offPeak": 50
    }
  },
  "본식 사회자": {
    "서울": {
      "peak": 33,
      "offPeak": 33
    },
    "수도권": {
      "peak": 30,
      "offPeak": 30
    },
    "광역시": {
      "peak": 30,
      "offPeak": 30
    },
    "이외": {
      "peak": 30,
      "offPeak": 30
    }
  },
  "주례": {
    "서울": {
      "peak": 20,
      "offPeak": 20
    },
    "수도권": {
      "peak": 18,
      "offPeak": 17
    },
    "광역시": {
      "peak": 15,
      "offPeak": 15
    },
    "이외": {
      "peak": 15,
      "offPeak": 15
    }
  },
  "축하공연 섭외": {
    "서울": {
      "peak": 80,
      "offPeak": 77
    },
    "수도권": {
      "peak": 69,
      "offPeak": 68
    },
    "광역시": {
      "peak": 53,
      "offPeak": 53
    },
    "이외": {
      "peak": 58,
      "offPeak": 57
    }
  },
  "본식 도우미": {
    "서울": {
      "peak": 32,
      "offPeak": 30
    },
    "수도권": {
      "peak": 24,
      "offPeak": 24
    },
    "광역시": {
      "peak": 25,
      "offPeak": 25
    },
    "이외": {
      "peak": 21,
      "offPeak": 21
    }
  },
  "폐백 음식": {
    "서울": {
      "peak": 38,
      "offPeak": 38
    },
    "수도권": {
      "peak": 38,
      "offPeak": 38
    },
    "광역시": {
      "peak": 17,
      "offPeak": 17
    },
    "이외": {
      "peak": 24,
      "offPeak": 24
    }
  },
  "폐백 수모": {
    "서울": {
      "peak": 16,
      "offPeak": 16
    },
    "수도권": {
      "peak": 15,
      "offPeak": 15
    },
    "광역시": {
      "peak": 10,
      "offPeak": 11
    },
    "이외": {
      "peak": 10,
      "offPeak": 10
    }
  },
  "한복 대여": {
    "서울": {
      "peak": 33,
      "offPeak": 33
    },
    "수도권": {
      "peak": 29,
      "offPeak": 29
    },
    "광역시": {
      "peak": 30,
      "offPeak": 30
    },
    "이외": {
      "peak": 28,
      "offPeak": 27
    }
  }
};
