// AUTO-GENERATED by scripts/build-pricing.mjs — do not edit by hand.
// CSV 갱신 시 `npm run build:pricing` 재실행 후 commit.
// 단위: 만원. `bojeung`만 인원수.

import type { ToggleId, UserRegion } from '../types';

export type TogglePriceSeason = {
  peak: number | null;
  offPeak: number | null;
};

export const TOGGLE_PRICES: Record<ToggleId, Record<UserRegion, TogglePriceSeason>> = {
  "원본 구매": {
    "서울": {
      "peak": 3,
      "offPeak": 3
    },
    "수도권": {
      "peak": 3,
      "offPeak": 3
    },
    "광역시": {
      "peak": 3,
      "offPeak": 3
    },
    "이외": {
      "peak": 3,
      "offPeak": 3
    }
  },
  "담당자 지정": {
    "서울": {
      "peak": 3,
      "offPeak": 3
    },
    "수도권": {
      "peak": 3,
      "offPeak": 3
    },
    "광역시": {
      "peak": 3,
      "offPeak": 3
    },
    "이외": {
      "peak": 3,
      "offPeak": 3
    }
  },
  "서브 스냅": {
    "서울": {
      "peak": 3,
      "offPeak": 3
    },
    "수도권": {
      "peak": 3,
      "offPeak": 3
    },
    "광역시": {
      "peak": 3,
      "offPeak": 3
    },
    "이외": {
      "peak": 3,
      "offPeak": 3
    }
  },
  "야외 촬영": {
    "서울": {
      "peak": 3,
      "offPeak": 3
    },
    "수도권": {
      "peak": 3,
      "offPeak": 3
    },
    "광역시": {
      "peak": 3,
      "offPeak": 3
    },
    "이외": {
      "peak": 3,
      "offPeak": 3
    }
  },
  "얼리스타트": {
    "서울": {
      "peak": 3,
      "offPeak": 3
    },
    "수도권": {
      "peak": 3,
      "offPeak": 3
    },
    "광역시": {
      "peak": 3,
      "offPeak": 3
    },
    "이외": {
      "peak": 3,
      "offPeak": 3
    }
  },
  "드레스 지정": {
    "서울": {
      "peak": 33,
      "offPeak": 38
    },
    "수도권": {
      "peak": 39,
      "offPeak": 45
    },
    "광역시": {
      "peak": 165,
      "offPeak": 165
    },
    "이외": {
      "peak": 151,
      "offPeak": 150
    }
  },
  "본식 헬퍼": {
    "서울": {
      "peak": 25,
      "offPeak": 25
    },
    "수도권": {
      "peak": 25,
      "offPeak": 25
    },
    "광역시": {
      "peak": 21,
      "offPeak": 21
    },
    "이외": {
      "peak": 23,
      "offPeak": 23
    }
  },
  "2부 드레스": {
    "서울": {
      "peak": 50,
      "offPeak": 50
    },
    "수도권": {
      "peak": 47,
      "offPeak": 48
    },
    "광역시": {
      "peak": 31,
      "offPeak": 31
    },
    "이외": {
      "peak": 31,
      "offPeak": 31
    }
  },
  "퍼스트웨어": {
    "서울": {
      "peak": 217,
      "offPeak": 222
    },
    "수도권": {
      "peak": 216,
      "offPeak": 220
    },
    "광역시": {
      "peak": 169,
      "offPeak": 171
    },
    "이외": {
      "peak": 193,
      "offPeak": 193
    }
  },
  "가봉 스냅": {
    "서울": {
      "peak": 77,
      "offPeak": 77
    },
    "수도권": {
      "peak": 77,
      "offPeak": 77
    },
    "광역시": {
      "peak": 81,
      "offPeak": 81
    },
    "이외": {
      "peak": 57,
      "offPeak": 57
    }
  },
  "턱시도 대여": {
    "서울": {
      "peak": 24,
      "offPeak": 24
    },
    "수도권": {
      "peak": 23,
      "offPeak": 23
    },
    "광역시": {
      "peak": 16,
      "offPeak": 16
    },
    "이외": {
      "peak": 15,
      "offPeak": 15
    }
  },
  "혼주 메이크업": {
    "서울": {
      "peak": 20,
      "offPeak": 20
    },
    "수도권": {
      "peak": 20,
      "offPeak": 20
    },
    "광역시": {
      "peak": 11,
      "offPeak": 11
    },
    "이외": {
      "peak": 14,
      "offPeak": 14
    }
  },
  "헤어변형": {
    "서울": {
      "peak": 35,
      "offPeak": 35
    },
    "수도권": {
      "peak": 35,
      "offPeak": 35
    },
    "광역시": {
      "peak": 27,
      "offPeak": 31
    },
    "이외": {
      "peak": 35,
      "offPeak": 38
    }
  },
  "생화 꽃장식": {
    "서울": {
      "peak": 515,
      "offPeak": 521
    },
    "수도권": {
      "peak": 413,
      "offPeak": 419
    },
    "광역시": {
      "peak": 156,
      "offPeak": 156
    },
    "이외": {
      "peak": 127,
      "offPeak": 129
    }
  },
  "부케": {
    "서울": {
      "peak": 29,
      "offPeak": 29
    },
    "수도권": {
      "peak": 29,
      "offPeak": 29
    },
    "광역시": {
      "peak": 19,
      "offPeak": 19
    },
    "이외": {
      "peak": 24,
      "offPeak": 24
    }
  },
  "플라워 샤워": {
    "서울": {
      "peak": 21,
      "offPeak": 118
    },
    "수도권": {
      "peak": 17,
      "offPeak": 95
    },
    "광역시": {
      "peak": 10,
      "offPeak": 40
    },
    "이외": {
      "peak": 10,
      "offPeak": 34
    }
  },
  "포토테이블": {
    "서울": {
      "peak": 36,
      "offPeak": 36
    },
    "수도권": {
      "peak": 33,
      "offPeak": 33
    },
    "광역시": {
      "peak": 37,
      "offPeak": 37
    },
    "이외": {
      "peak": 37,
      "offPeak": 37
    }
  },
  "웨딩 케이크": {
    "서울": {
      "peak": 43,
      "offPeak": 43
    },
    "수도권": {
      "peak": 41,
      "offPeak": 40
    },
    "광역시": {
      "peak": 30,
      "offPeak": 30
    },
    "이외": {
      "peak": 33,
      "offPeak": 32
    }
  },
  "본식 사회자": {
    "서울": {
      "peak": 33,
      "offPeak": 33
    },
    "수도권": {
      "peak": 30,
      "offPeak": 30
    },
    "광역시": {
      "peak": 30,
      "offPeak": 30
    },
    "이외": {
      "peak": 30,
      "offPeak": 30
    }
  },
  "주례": {
    "서울": {
      "peak": 20,
      "offPeak": 20
    },
    "수도권": {
      "peak": 17,
      "offPeak": 17
    },
    "광역시": {
      "peak": 15,
      "offPeak": 15
    },
    "이외": {
      "peak": 15,
      "offPeak": 15
    }
  },
  "축하공연 섭외": {
    "서울": {
      "peak": 82,
      "offPeak": 82
    },
    "수도권": {
      "peak": 70,
      "offPeak": 70
    },
    "광역시": {
      "peak": 54,
      "offPeak": 54
    },
    "이외": {
      "peak": 57,
      "offPeak": 57
    }
  },
  "본식 도우미": {
    "서울": {
      "peak": 31,
      "offPeak": 31
    },
    "수도권": {
      "peak": 23,
      "offPeak": 23
    },
    "광역시": {
      "peak": 24,
      "offPeak": 24
    },
    "이외": {
      "peak": 21,
      "offPeak": 21
    }
  },
  "폐백 음식": {
    "서울": {
      "peak": 38,
      "offPeak": 38
    },
    "수도권": {
      "peak": 38,
      "offPeak": 39
    },
    "광역시": {
      "peak": 17,
      "offPeak": 17
    },
    "이외": {
      "peak": 24,
      "offPeak": 24
    }
  },
  "폐백 수모": {
    "서울": {
      "peak": 16,
      "offPeak": 16
    },
    "수도권": {
      "peak": 15,
      "offPeak": 15
    },
    "광역시": {
      "peak": 10,
      "offPeak": 10
    },
    "이외": {
      "peak": 10,
      "offPeak": 10
    }
  },
  "한복 대여": {
    "서울": {
      "peak": 33,
      "offPeak": 33
    },
    "수도권": {
      "peak": 30,
      "offPeak": 30
    },
    "광역시": {
      "peak": 31,
      "offPeak": 31
    },
    "이외": {
      "peak": 28,
      "offPeak": 27
    }
  }
};
